export const products = {
  produce: {
    items: [
      'Apples',
      'Strawberries',
      'Tomatoes',
      'Blueberries',
      'Cashews',
      'Onions',
      'Carrots',
      'Broccolini',
      'Avocado',
      'Oranges',
      'Potatoes',
      'Bananas',
    ],
  },
  deli: {
    items: [
      'Whole roast chicken',
      'Microwave meal',
      'Chicken thigh kg',
      'Chicken breast kg',
      'Shredded chicken breast',
      'Sundried tomatoes',
    ],
  },
  perishables: {
    items: [
      'Chobani 1L',
      'Chobani 200g',
      'Chobani Fit',
      'Cottage Cheese',
      'Shaved Ham',
      'Kabana',
      'Salmon',
      'Iced Coffee',
    ],
  },
  meat: {
    items: ['Minced beef', 'Pork chops', 'Kangaroo', 'Lamb chunks'],
  },
  grocery: {
    items: [
      'Peanut Butter',
      'Oats',
      'Gladwrap',
      'Freezer bags',
      'Chips',
      'Savoys',
      'Pasta shells',
      'Pasta sauce',
      'Tomato paste',
      'Noodles',
      'Rice',
      'Salt',
      'Pepper',
      'Cooking oil',
      'Spices',
      'Tuna',
    ],
  },
  bathroom: {
    items: [
      'Deoderant',
      'Shampoo',
      'Body wash',
      'Toothpaste',
      'Mouthwash',
      'Floss',
      'Shaving cream',
      'Shaving razor',
      'Hand soap',
      'Hand sanitiser',
      'Sunscreen',
      'Tissues',
      'Socks',
      'Underpants',
    ],
  },
  cleaning: {
    items: [
      'Washing machine cleaner',
      'Laundry detergent',
      'Carpet cleaner',
      'All-purpose cleaner',
      'Toilet cleaner',
      'Sponge',
      'Towel',
      'Paper towels',
      'Toilet paper',
    ],
  },
  freezer: {
    items: [
      'Pre-packed veggies',
      'Hot bandito wedges',
      'Camel pies',
      'Ice cream',
    ],
  },
};
